In [1]:
import tensorflow as tf
tf.__version__

C:\Users\Ayman\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Ayman\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Ayman\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Ayman\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Ayman\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Ayman\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

'2.3.0'

In [2]:
from tensorflow.python.client import device_lib 
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1102132356381748733
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 1308239327636153287
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 8962639014185267413
physical_device_desc: "device: XLA_GPU device"
]

In [3]:
# config = tf.ConfigProto()

In [4]:
import os 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
path = os.path.join('data','input_bcell_numerical.csv')
df = pd.read_csv(path)
df

,parent_protein_id,start_position,end_position,chou_fasman,emini,kolaskar_tongaonkar,parker,isoelectric_point,aromaticity,hydrophobicity,stability,target,protein_seq_mass
0,A2T3T0,161,165,1.016,0.703,1.018,2.220,5.810364,0.103275,-0.143829,40.273300,1,51950
1,F0V2I4,251,255,0.770,0.179,1.199,-3.860,6.210876,0.065476,-0.036905,24.998512,1,42734
2,O75508,145,149,0.852,3.427,0.960,4.280,8.223938,0.091787,0.879227,27.863333,1,25675
3,O84462,152,156,1.410,2.548,0.936,6.320,4.237976,0.044776,-0.521393,30.765373,1,120095
4,P00918,85,89,1.214,1.908,0.937,4.640,6.867493,0.103846,-0.578846,21.684615,1,33875
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14382,Q91DE1,177,191,0.910,0.175,1.054,0.820,4.894836,0.071719,-0.701083,46.875237,0,96654
14383,Q91DE1,285,299,0.966,0.216,1.044,1.160,4.894836,0.071719,-0.701083,46.875237,0,96654
14384,Q91DE1,189,203,0.821,0.023,1.044,-1.360,4.894836,0.071719,-0.701083,46.875237,0,96654
14385,Q9QZS0,1479,1493,1.069,0.239,1.037,2.180,9.553040,0.044338,-0.671001,29.494308,0,191567
14386,Q9QZS0,1647,1661,0.962,0.257,1.045,2.127,9.553040,0.044338,-0.671001,29.494308,1,191567

In [6]:
df_1 = df.drop(['parent_protein_id'], axis=1)
df_1

,start_position,end_position,chou_fasman,emini,kolaskar_tongaonkar,parker,isoelectric_point,aromaticity,hydrophobicity,stability,target,protein_seq_mass
0,161,165,1.016,0.703,1.018,2.220,5.810364,0.103275,-0.143829,40.273300,1,51950
1,251,255,0.770,0.179,1.199,-3.860,6.210876,0.065476,-0.036905,24.998512,1,42734
2,145,149,0.852,3.427,0.960,4.280,8.223938,0.091787,0.879227,27.863333,1,25675
3,152,156,1.410,2.548,0.936,6.320,4.237976,0.044776,-0.521393,30.765373,1,120095
4,85,89,1.214,1.908,0.937,4.640,6.867493,0.103846,-0.578846,21.684615,1,33875
...,...,...,...,...,...,...,...,...,...,...,...,...
14382,177,191,0.910,0.175,1.054,0.820,4.894836,0.071719,-0.701083,46.875237,0,96654
14383,285,299,0.966,0.216,1.044,1.160,4.894836,0.071719,-0.701083,46.875237,0,96654
14384,189,203,0.821,0.023,1.044,-1.360,4.894836,0.071719,-0.701083,46.875237,0,96654
14385,1479,1493,1.069,0.239,1.037,2.180,9.553040,0.044338,-0.671001,29.494308,0,191567
14386,1647,1661,0.962,0.257,1.045,2.127,9.553040,0.044338,-0.671001,29.494308,1,191567

In [7]:
X = df_1.drop('target',axis=1)
y = df_1.target.values.reshape(-1,1)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
X_train.shape[1]

11

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from tensorflow.keras.utils import to_categorical
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=11))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=256, activation='relu'))
model.add(Dense(units=512, activation='relu'))
model.add(Dense(units=1048, activation='relu'))
model.add(Dense(units=2048, activation='relu'))
model.add(Dense(units=2048, activation='relu'))
model.add(Dense(units=2048, activation='relu'))
model.add(Dense(units=2048, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

print(model.summary())

model.fit(
    X_train,
    y_train_categorical,
    batch_size=512,
    epochs=300,
    shuffle=True,
    verbose=2
)


print('\n----------------------------------------------------------------\n')

model_loss, model_accuracy = model.evaluate(
X_test, y_test_categorical, verbose=2)
print(f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_20 (Dense)             (None, 64)                768
_________________________________________________________________
dense_21 (Dense)             (None, 128)               8320
_________________________________________________________________
dense_22 (Dense)             (None, 256)               33024
_________________________________________________________________
dense_23 (Dense)             (None, 512)               131584
_________________________________________________________________
dense_24 (Dense)             (None, 1048)              537624
_________________________________________________________________
dense_25 (Dense)             (None, 2048)              2148352
_________________________________________________________________
dense_26 (Dense)             (None, 2048)              4196352
_________________________________________________________________
dense_27 (Dense)             (None, 2048)              4196352
_________________________________________________________________
dense_28 (Dense)             (None, 2048)              4196352
_________________________________________________________________
dense_29 (Dense)             (None, 2)                 4098
=================================================================
Total params: 15,452,826
Trainable params: 15,452,826
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/300
23/23 - 6s - loss: 871.8584 - accuracy: 0.5591
Epoch 2/300
23/23 - 6s - loss: 5.1798 - accuracy: 0.6129
Epoch 3/300
23/23 - 6s - loss: 0.7104 - accuracy: 0.6760
Epoch 4/300
23/23 - 6s - loss: 0.6104 - accuracy: 0.7273
Epoch 5/300
23/23 - 6s - loss: 0.6068 - accuracy: 0.7273
Epoch 6/300
23/23 - 6s - loss: 0.6020 - accuracy: 0.7273
Epoch 7/300
23/23 - 6s - loss: 0.5978 - accuracy: 0.7273
Epoch 8/300
23/23 - 6s - loss: 0.5938 - accuracy: 0.7273
Epoch 9/300
23/23 - 7s - loss: 0.5929 - accuracy: 0.7273
Epoch 10/300
23/23 - 7s - loss: 0.5903 - accuracy: 0.7273
Epoch 11/300